Hotfix for #233047 - NoClassDefFoundError: Could not initialize class org.netbeans.modules.extbrowser.NbDefaultUnixBrowserImpl
The fix needs to be improved.