Trying to avoid random failures of ChildrenFilterAsKeysTest.testSlowRemoveNotify with message "Remove notify is being called expected:<1> but was:<0>" by keeping strong reference to the WeakReference that implements is later feeded into active reference queue.