Improving support for Netbinox & Mylyn, useful for including IDE subsets in NetBeansInOSGi. Still a number of linkage errors and other errors during startup of full IDE; none seem fatal, but the following prevents BZ connections from being made: java.lang.NoClassDefFoundError: javax/security/auth/login/LoginException 	at org.eclipse.mylyn.internal.bugzilla.core.BugzillaClientFactory.createClient(BugzillaClientFactory.java:32) 	at org.eclipse.mylyn.internal.bugzilla.core.BugzillaClientManager.createClient(BugzillaClientManager.java:74) 	at org.eclipse.mylyn.internal.bugzilla.core.BugzillaClientManager.getClient(BugzillaClientManager.java:60) 	at org.netbeans.modules.bugzilla.commands.ValidateCommand.execute(ValidateCommand.java:72) 	at org.netbeans.modules.bugzilla.commands.BugzillaExecutor.execute(BugzillaExecutor.java:114) 	at org.netbeans.modules.bugzilla.repository.RepositoryController$2.execute(RepositoryController.java:327) 	at org.netbeans.modules.bugzilla.repository.RepositoryController$TaskRunner.run(RepositoryController.java:385) 	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1424) 	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1973) Caused by: java.lang.ClassNotFoundException: javax.security.auth.login.LoginException not found by org.eclipse.mylyn.bugzilla.core [30] 	at org.apache.felix.framework.ModuleImpl.findClassOrResourceByDelegation(ModuleImpl.java:812) 	at org.apache.felix.framework.ModuleImpl.access$400(ModuleImpl.java:72) 	at org.apache.felix.framework.ModuleImpl$ModuleClassLoader.loadClass(ModuleImpl.java:1807) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) 	... 9 more