#194917: NoClassDefFoundError: Could not initialize class java.awt.dnd.DragSource due to CLIOptions2$EQStuck: GUI is not responsive Do not stop EQ when inside a statjc initializer, as it can lead to later NCDFE's. (Try interrupting the thread, which could be enough in some cases.) Also increasing timeout a bit from ten to fifteen seconds.