Issue #224117 - NoSuchMethodError: org.netbeans.modules.kenai.ui.api.KenaiUIUtils.getDashboardProjects()[Lorg/netbeans/modules/team/ui/spi/ProjectHandle; increasing spec version to force the module's update from UC